# ISLR - linear regression - lab
library(MASS)
library(ISLR)
fix(Boston)
names(Boston)
lm.fit=lm(medv~lstat, Boston)
attach(Boston)
lm.fit
summary(lm.fit)
names(lm.fit)
coef(lm.fit)
confint(lm.fit)
predict(lm.fit, data.frame(lstat=c(5,10,15)), interval='confidence')
predict(lm.fit, data.frame(lstat=c(5,10,15)), interval='prediction')
plot(lstat, medv)
abline(lm.fit, col='red', lwd=3)
plot(lstat, medv, col='red')
plot(lstat, medv, pch=20)
plot(lstat, medv, pch='+')
plot(1:20, 1:20, pch=1:20, col=1:20)
par(mfrow=c(2,2))
plot(lm.fit)
par(mfrow=c(1,2))
plot(predict(lm.fit), residuals(lm.fit))
plot(predict(lm.fit), rstudent(lm.fit))
par(mfrow=c(1,1))
plot(hatvalues(lm.fit))
which.max(hatvalues(lm.fit))
lm.fit2=lm(medv~lstat+age, data=Boston)
summary(lm.fit2)
lm.fit3=lm(medv~., data=Boston)
summary(lm.fit3)
summary(lm.fit3)$r.sq
summary(lm.fit3)$sigma
library(car)
vif(lm.fit3)
lm.fit4=lm(medv~.-age, data=Boston)
summary(lm.fit4)
lm.fit4=update(lm.fit3, ~.-age)
summary(lm.fit4)
summary(lm(medv~lstat*age, data=Boston))
lm.fit5=lm(medv~lstat+I(lstat^2))
summary(lm.fit5)
lm.fit6=lm(medv~lstat)
anova(lm.fit6, lm.fit5)
par(mfrow=c(2,2))
plot(lm.fit5)
lm.fit7=lm(medv~poly(lstat,5))
summary(lm.fit7)
summary(lm(medv~log(rm), data=Boston))

fix(Carseats)        
lm.fit=lm(Sales~.+Income:Advertising+Price:Age, data=Carseats)
# : for interaction
summary(lm.fit)
attach(Carseats)
contrasts(ShelveLoc)
# contrast() returns coding fot dummy variables

LoadLibraries=function(){
  library(ISLR)
  library(MASS)
  print('The libraries have been loaded.')
}
LoadLibraries
LoadLibraries()
